# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u7528\u6237\u540d')),
                ('passwd', models.CharField(max_length=128, verbose_name='\u5bc6\u7801')),
                ('passwd2', models.CharField(max_length=128, verbose_name='\u91cd\u590d\u5bc6\u7801')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('phone', models.CharField(max_length=128, verbose_name='\u624b\u673a\u53f7')),
                ('verticode', models.CharField(max_length=128, verbose_name='\u624b\u673a\u53f7')),
            ],
        ),
    ]
